---
version: 2
jobs:
  build: &build
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install -e .
  test: &test
    docker:
      - image: circleci/python:3.7.0
      - image: influxdb:latest
    steps:
      - checkout
      - run:
          name: Install test extras
          command: sudo pip install -e .[test]
      - run:
          name: Run test
          command: make test
      - run:
          name: Install pandas extras
          command: sudo pip install -e .[pandas]
      - run:
          name: Run test again (w/ Pandas support)
          command: make test
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)
  build-3.6:
    <<: *build
    docker:
      - image: circleci/python:3.6.6
  test-3.6:
    <<: *test
    docker:
      - image: circleci/python:3.6.6
      - image: influxdb:latest
  build-3.5:
    <<: *build
    docker:
      - image: circleci/python:3.5.5
  test-3.5:
    <<: *test
    docker:
      - image: circleci/python:3.5.5
      - image: influxdb:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_and_test-3.6:
    jobs:
      - build-3.6
      - test-3.6:
          requires:
            - build-3.6
  build_and_test-3.5:
    jobs:
      - build-3.5
      - test-3.5:
          requires:
            - build-3.5
